language: cpp

services:
  - xvfb

cache:
 apt: true

env:
  - RUN_TESTS=false USE_VTK=OFF

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - tcl-dev
      - tk-dev
      - libgl2ps-dev
      - libfreeimage-dev
      - libtbb-dev
      - tclthread
      - libgl1-mesa-dev
      - libxmu-dev
      - libxi-dev
      - xsltproc
      - doxygen
      - ninja-build
      - libvtk6-dev
      - graphviz
      
matrix:
  include:
  - os: linux
    compiler: gcc
    env: USE_VTK=ON
    dist: xenial
  - os: linux
    compiler: gcc
    env: USE_VTK=ON
    dist: bionic
  - os: linux
    compiler: gcc
    env: USE_VTK=OFF
    dist: focal
  - os: linux
    compiler: gcc
    env: USE_VTK=ON
    dist: focal
  - os: linux
    compiler: clang
    env: USE_VTK=ON
    dist: focal
  - os: osx
    osx_image: xcode11.6
    compiler: clang
  - os: osx
    osx_image: xcode12
    compiler: clang
  - os: osx
    osx_image: xcode9.3beta
    compiler: clang

before_install:
  # osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install freetype;
        brew install freeimage;
        brew install gl2ps;
        brew install doxygen;
        brew install graphviz;
    fi
  # linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        eval "${MATRIX_EVAL}";
    fi

script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake .. -DUSE_VTK=$USE_VTK -USE_FREEIMAGE=ON -DBUILD_USE_PCH=ON
  - make -j3
  - sudo make install

after_script:
  - test ! -r occt/summary.xml || xsltproc --param duration 1 ../.travis.xsl occt/summary.xml
  - if [ -r occt/summary.xml ]; then
        xsltproc ../.travis.xsl occt/summary.xml > occt/summary.failed;
        if [ -s occt/summary.failed ]; then
            echo "FAILED TESTS:";
            cat occt/summary.failed;
            for file in $(cat occt/summary.failed); do head -n -1 occt/$file.{tcl,log}; done;
        fi;
    fi

branches:
  only:
    - master
    - /^review/
    - oce/patches
